name    'conzar/check_run'
version '0.2.2'
source 'https://github.com/Conzar/check_run'
author 'Michael Speth'
license 'GPLv3'
summary 'A helper module that checks if a command has been run'
description 'Should be used by other modules to check if a task has been run.'
project_page 'https://github.com/Conzar/check_run'
